###Get latitude, longitude, and zone
GET http://phzmapi.org/44111.json

###Getting the station id
GET https://api.farmsense.net/v1/frostdates/stations/?lat=30.62&lon=-87.89

###Getting the frost date
GET https://api.farmsense.net/v1/frostdates/probabilities/?station=12813&season=1

### Getting all recipes
GET https://api.edamam.com/api/recipes/v2?type=public&q=lettuce&app_id=2762fe12&app_key=9a0f0246c250ede5b70c49d6ee4d1116

###
GET https://api.edamam.com/api/recipes/v2?type=public&q=chicken&app_id=2762fe12&app_key=9a0f0246c250ede5b70c49d6ee4d1116&cont=2&field=uri&field=label&field=image&field=source&field=url

###
GET https://api.edamam.com/api/recipes/v2?type=public&q=chicken&app_id=2762fe12&app_key=9a0f0246c250ede5b70c49d6ee4d1116&field=label

###Returns All Plant info:
GET http://localhost:8080/

###
GET  http://localhost:8080/plant/2

###
GET  http://localhost:8080/plants?plantsIds=1,2,5,30,